### ISSUE TITLE
Switch2 widget: new version

### ISSUE THREAD

**Issue by schnupperm** [EdgeTX/lua-scripts#12]
Hello,

I've made a new version of my widget.
Link to rc-groups:
https://www.rcgroups.com/forums/showpost.php?p=50176699&postcount=4012

Link to repository.justfly.solutions:
https://repository.justfly.solutions/index.php?view=product&id=115:switch-config

**Comment by pfeerick** [comment]
Thanks for the update... and also for the great widget :)
