### ISSUE TITLE
where is the wizard lua script

### ISSUE THREAD

**Issue by ror1948** [EdgeTX/lua-scripts#19]
where is the wizard lua script
thanks

**Comment by pfeerick** [comment]
On the sdcard pack. https://github.com/EdgeTX/edgetx-sdcard/

**Comment by ror1948** [comment]
oh ok i see them they are under templatesi was looking in tools.
thanks

    On Saturday, May 11, 2024 at 11:30:58 p.m. EDT, Peter Feerick ***@***.***> wrote:  
 
 


On the sdcard pack. https://github.com/EdgeTX/edgetx-sdcard/

**Comment by ror1948** [comment]
bug in multirotor wizard under templatetried to create new model multirotor


    On Saturday, May 11, 2024 at 11:30:58 p.m. EDT, Peter Feerick ***@***.***> wrote:  
 
 


On the sdcard pack. https://github.com/EdgeTX/edgetx-sdcard/
